# constants.py

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

HEX_SIZE = 38
MAP_COLS = 11
MAP_ROWS = 8

CAMP_POSITION = (5, 4)
START_POSITION = CAMP_POSITION

MAX_DAY_ACTIONS = 6

RESOURCE_FOOD = "food"
RESOURCE_WOOD = "wood"
RESOURCE_STONE = "stone"
RESOURCE_HIDE = "hide"

TERRAIN_GRASS = "grass"
TERRAIN_FOREST = "forest"
TERRAIN_ROCK = "rock"
TERRAIN_WATER = "water"

SPECIAL_REWARD = "reward"
SPECIAL_TRAP = "trap"

STATE_DAY = "day"
STATE_NIGHT = "night"
STATE_GAME_OVER = "game_over"

ACTION_MOVE_COST = 1
ACTION_GATHER_COST = 1
ACTION_BUILD_COST = 2
ACTION_CRAFT_COST = 2
ACTION_EAT_COST = 1
ACTION_FIREWOOD_COST = 1